# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cue < Formula
  desc "CUE is an open source data constraint language which aims to simplify tasks involving defining and using data."
  homepage "https://cuelang.org"
  version "0.4.1-beta.4"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/cue-lang/cue/releases/download/v0.4.1-beta.4/cue_v0.4.1-beta.4_darwin_amd64.tar.gz"
      sha256 "9e0dfac7930d6424bdd11322e439aa22188adc4a9474c343715578a5ea6d65bf"

      def install
        bin.install "cue"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/cue-lang/cue/releases/download/v0.4.1-beta.4/cue_v0.4.1-beta.4_darwin_arm64.tar.gz"
      sha256 "3b33443753f55fa6549ce93110675b086ae8494733cd852ce9a9b610b95e43d7"

      def install
        bin.install "cue"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/cue-lang/cue/releases/download/v0.4.1-beta.4/cue_v0.4.1-beta.4_linux_arm64.tar.gz"
      sha256 "dd656ebab73c90e2bcbfc933f7bc539710f7b6c13defabec688beb9494e281b4"

      def install
        bin.install "cue"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/cue-lang/cue/releases/download/v0.4.1-beta.4/cue_v0.4.1-beta.4_linux_amd64.tar.gz"
      sha256 "8d4a5c4b88e38ccf5cc2dc667f5b59d94cef73a24d9c26de0ad5b5792da1922a"

      def install
        bin.install "cue"
      end
    end
  end

  test do
    system "#{bin}/cue version"
  end
end
