# This file was generated by GoReleaser. DO NOT EDIT.
class Cue < Formula
  desc "CUE is an open source data constraint language which aims to simplify tasks involving defining and using data."
  homepage "https://github.com/cuelang/cue"
  version "0.0.5"

  if OS.mac?
    url "https://github.com/cuelang/cue/releases/download/v0.0.5/cue_0.0.5_Darwin_x86_64.tar.gz"
    sha256 "31a7eaee424ad63107540c4ea326e426e5459f768b67801368a244f0b3648d41"
  elsif OS.linux?
    url "https://github.com/cuelang/cue/releases/download/v0.0.5/cue_0.0.5_Linux_x86_64.tar.gz"
    sha256 "89404535beb739919062c699b766ab2c9d799f2ca1fa2dc58c0efc85c1ebac20"
  end

  def install
    bin.install "cue"
  end

  test do
    system "#{bin}/cue version"
  end
end
